insert into public.recipes (
  id, name, blurb, cuisine, source, cook_time_minutes,
  servings, hue, tags, one_pan, make_ahead, added_at, ingredients, steps
) values
  ('chopped-greek-salad', 'Chopped Greek Salad', 'No lettuce. Real Greek salad never had any.', 'other', '{"type":"instagram","label":"Instagram"}'::jsonb, 15, 4, 196, array['salad', 'healthy', 'weeknight', 'vegetarian']::text[], false, false, '2026-08-16', '[{"quantity":4,"unit":"medium","item":"ripe tomatoes","category":"produce"},{"quantity":1,"unit":"large","item":"cucumber","category":"produce"},{"quantity":1,"unit":"medium","item":"red onion","category":"produce"},{"quantity":1,"unit":"medium","item":"green bell pepper","category":"produce"},{"quantity":7,"unit":"oz","item":"block feta","category":"dairy"},{"quantity":0.5,"unit":"cup","item":"Kalamata olives","category":"pantry"},{"quantity":4,"unit":"tbsp","item":"olive oil","category":"pantry"},{"quantity":1,"unit":"tbsp","item":"red wine vinegar","category":"pantry"},{"quantity":1,"unit":"tsp","item":"dried oregano","category":"spices"}]'::jsonb, '["Cut the tomatoes into thick wedges and salt them in the serving bowl. Leave them ten minutes — the liquid they give up is half the dressing.","Peel the cucumber in stripes and cut it into thick half-moons. Thin slices go limp.","Slice the onion as finely as you can manage and rinse it under cold water to take the raw edge off.","Add the pepper, olives, and everything else to the tomatoes with the oil, vinegar, and oregano.","Lay the feta on top as a whole slab rather than crumbling it, and dust it with more oregano.","Serve immediately, with bread for the liquid at the bottom."]'::jsonb),
  ('kale-caesar-crispy-chickpeas', 'Kale Caesar with Crispy Chickpeas', 'Massage the kale properly and it stops tasting like a punishment.', 'other', '{"type":"tiktok","label":"TikTok"}'::jsonb, 25, 4, 118, array['salad', 'healthy', 'weeknight', 'vegetarian']::text[], false, false, '2026-08-12', '[{"quantity":2,"unit":"bunch","item":"lacinato kale","category":"produce"},{"quantity":1,"unit":"can","item":"chickpeas","category":"pantry"},{"quantity":3,"unit":"tbsp","item":"olive oil","category":"pantry"},{"quantity":0.5,"unit":"cup","item":"grated parmesan","category":"dairy"},{"quantity":0.25,"unit":"cup","item":"Greek yogurt","category":"dairy"},{"quantity":2,"unit":"clove","item":"garlic","category":"produce"},{"quantity":1,"unit":"whole","item":"lemon","category":"produce"},{"quantity":1,"unit":"tsp","item":"Dijon mustard","category":"pantry"},{"quantity":1,"unit":"tsp","item":"smoked paprika","category":"spices"}]'::jsonb, '["Dry the chickpeas thoroughly, toss with a spoon of oil and the paprika, and roast at 425°F for 20 minutes until they rattle in the pan.","Strip the kale off its stems and shred it finely.","Add a pinch of salt and a little oil and massage the leaves with your hands for a full minute. They will darken and halve in volume — that is the point, and skipping it is why most kale salads are unpleasant.","Whisk the yogurt, grated garlic, lemon juice, mustard, and most of the parmesan into a dressing that just coats a spoon.","Toss the kale through the dressing and leave it five minutes to soften further.","Top with the crispy chickpeas and the last of the parmesan."]'::jsonb),
  ('quinoa-tabbouleh', 'Quinoa Tabbouleh', 'Overwhelmingly parsley, faintly grain. That ratio is not a mistake.', 'other', '{"type":"blog","label":"seriouseats.com"}'::jsonb, 20, 6, 88, array['salad', 'healthy', 'vegetarian']::text[], false, true, '2026-08-07', '[{"quantity":0.75,"unit":"cup","item":"quinoa","category":"pantry"},{"quantity":3,"unit":"bunch","item":"flat-leaf parsley","category":"produce"},{"quantity":0.5,"unit":"bunch","item":"mint","category":"produce"},{"quantity":3,"unit":"medium","item":"ripe tomatoes","category":"produce"},{"quantity":4,"unit":"stalk","item":"scallions","category":"produce"},{"quantity":2,"unit":"whole","item":"lemons","category":"produce"},{"quantity":5,"unit":"tbsp","item":"olive oil","category":"pantry"},{"quantity":0.5,"unit":"tsp","item":"ground allspice","category":"spices"}]'::jsonb, '["Rinse the quinoa well, simmer it 12 minutes, then spread it on a tray to cool and dry out. Warm quinoa wilts the herbs.","Wash and dry the parsley completely, then chop it as finely as your knife allows. Wet herbs bruise into a paste.","Deseed the tomatoes and dice them small, discarding the watery centres so the salad does not flood.","Combine the herbs, tomatoes, sliced scallions, and cooled quinoa.","Dress with lemon juice, olive oil, allspice, and a generous amount of salt. It should taste sharper than seems sensible.","Rest 20 minutes before serving so the grain takes on the dressing."]'::jsonb)
on conflict (id) do update set
  name = excluded.name, blurb = excluded.blurb, cuisine = excluded.cuisine,
  source = excluded.source, cook_time_minutes = excluded.cook_time_minutes,
  servings = excluded.servings, hue = excluded.hue, tags = excluded.tags,
  one_pan = excluded.one_pan, make_ahead = excluded.make_ahead,
  added_at = excluded.added_at, ingredients = excluded.ingredients,
  steps = excluded.steps;
